services:
  app:
    image: kooldev/node:14-nest
    command: ["npm", "run", "start:dev"]
    ports:
      - "${KOOL_APP_PORT:-3000}:3000"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    #  - $HOME/.ssh:/home/kool/.ssh:delegated ???
    networks:
      - kool_local
      - kool_global
