# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'Typescript' ]

name: 'AdonisJS'

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new Adonis Application
    actions:
      - prompt: 'Which Javascript package manager do you want to use for starter kit creation?'
        ref: 'javascript_package_manager'
        default: 'npm'
        options:
          - name: 'npm'
            actions:
              - scripts:
                - docker pull -q kooldev/node:20
                - kool docker kooldev/node:20 npm init -y adonis-ts-app@latest $CREATE_DIRECTORY
          - name: 'yarn'
            actions:
              - scripts:
                - docker pull -q kooldev/node:20
                - kool docker kooldev/node:20 yarn create adonis-ts-app $CREATE_DIRECTORY
          - name: 'bun'
            actions:
              - scripts:
                - docker pull -q oven/bun:1
                - kool docker --user $KOOL_ASUSER --env HOME=/tmp oven/bun:1 bun create adonis-ts-app $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: docker-compose.yml
      - copy: kool.yml

  - name: 'Customize your setup'
    actions:
      - recipe: pick-db
      - recipe: pick-cache
      # define package manager
      - prompt: Which javascript package manager do you want to use?
        ref: 'javascript_package_manager'
        default: 'npm'
        options:
          - name: 'npm'
            actions:
              - merge: app/node-adonis.yml
                dst: docker-compose.yml
              - merge: scripts/npm-adonis.yml
                dst: kool.yml
          - name: 'yarn'
            actions:
              - merge: app/node-adonis.yml
                dst: docker-compose.yml
              - merge: scripts/yarn-adonis.yml
                dst: kool.yml
          - name: 'bun'
            actions:
              - merge: app/bun-adonis.yml
                dst: docker-compose.yml
              - merge: scripts/bun-adonis.yml
                dst: kool.yml
